### ISSUE TITLE
Add airframe capabilities rating scale per mission type

### ISSUE THREAD

**Issue by rabauke80** [dcs-liberation/dcs_liberation#2199]
Since ED changes capabilities by adding/changing loadouts and the fact that the AI can handle certain things better than other, this would be an easy way to make adjustments helping the autoplanner

The goal is to support the auto planner in picking the right stuff - especially in concurrency scenarios, where it has multiple identical options available to chose from

I was thinking of a _capabilities grading_ per airframe and mission task, from 1 (least capable) to 10 (most capable). Based on the squadrons assigned tasks and the airframes capabilities, the auto planner could then go in an pick the best available fit.

This could be used to reduce the overall AI spam of flights.

example with random numbers for the A-10C II and the mission types example picked from a squadron below:

```
always_keeps_gun: true
description:
  The A-10C Thunderbolt II, also known as the Warthog, is a 'flying gun'.
  The A-10C is a high-survivability and versatile aircraft, popular with pilots for
  the 'get home' effectiveness.The mission of the aircraft is ground attack against
  tanks, armored vehicles and installations, and close air support of ground forces.
  The Warthog is famous for its massive 30mm cannon, but it can also be armed with
  Maverick guided missiles and several types of bombs and rockets.
introduced: 2012
manufacturer: Fairchild Republic
origin: USA
price: 20
role: Close Air Support/Attack
capabilities:
  - BAI [7]
  - CAS [10]
  - DEAD [8]
  - OCA/Aircraft [7]
  - OCA/Runway [5]
  - Strike [3]
variants:
  A-10C Thunderbolt II (Suite 7): {}
radios:
  # VHF for intraflight is not accepted anymore by DCS
  # (see https://forums.eagle.ru/showthread.php?p=4499738).
  intra_flight: AN/ARC-164
  inter_flight: AN/ARC-164
```

```
---
name: 81st FS
nickname: Termites
female_pilot_percentage: 6
country: USA
role: Close Air Support
aircraft: A-10C Thunderbolt II (Suite 7)
livery: 81st FS Spangdahlem AB, Germany (SP) 2
mission_types:
  - BAI
  - CAS
  - DEAD
  - OCA/Aircraft
  - OCA/Runway
  - Strike
```
