### ISSUE TITLE
Not possible to set laser codes for F-15E S4+

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#3090]
### Affected versions

Development build

### Build information

Local build 1f73e02d1507af4e5b364eb1170346cbb4c7c05c

### Description

It's not possible to set valid laser codes for the strike eagle in the liberation UI. All the other jets did this as 3 separate 0-9 fields (one per digit after the required leading `1`), but the strike eagle has fields like "Laser code for Station 2 1xxx" with a min value of 111, a max of 888, and a default of 688. Because numbers above 9 aren't valid for this UI element, those end up truncated, and possibly (I haven't tested) stored wrong in the miz as a result.

pydcs doesn't currently have the data for us to do better, but the data is available is available:

```yaml
          6:
            "dimension": " "
            "label": "Laser code for Station 2 1xxx"
            "id": "Sta2LaserCode"
            "min": 111
            "max": 888
            "control": "spinbox"
            "defValue": 688
```

Bonus points: useful names are apparently also available, but not yet in pydcs. I would never have guessed that `HumanOrchestra` meant "Disable Multicrew".

![image](https://github.com/dcs-liberation/dcs_liberation/assets/315852/79610fda-c0ab-4833-b809-5b1655727d1c)

### Save game and other files (save game required, bugs without saves will be closed)

[wrong strike eagle props.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12101158/wrong.strike.eagle.props.liberation.zip)
